baseURL = 'https://www.tainguyen.com/'
languageName = "VN"
languageCode = 'vi-VN'
defaultContentLanguage = "vi"
title = 'Tài Nguyên'
theme = 'dream'

[permalinks]
    posts = "/:year/:month/:slug/"
    page = "/:slug/"
 [permalinks.page]
    posts = '/articles/:year/:month/:slug/'
    tutorials = '/training/:slug/'
  [permalinks.section]
    posts = '/articles/'
    tutorials = '/training/'

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "narga"
description = "Tôi biết, bạn cũng biết"
# avatar = "img/avatar.png"
headerTitle = "Tài Nguyên"
motto = "Tôi biết, bạn cũng biết"

footerBottomText = '''
Bản quyền về Nội dung © 2003-2024 tuân theo giấy phép <a href="https://web.archive.org/web/20171005084255/https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank" rel="noopener noreferrer">CC BY-NC-ND 4.0</a>.<br> <span> <strong>TRÍCH</strong> dẫn nguyên vẹn, <strong>PHẢI</strong> ghi rõ <strong>NGUỒN</strong>, chỉ <strong>DÙNG</strong> cá nhân, <strong>KHÔNG</strong> được tính phí.</span>
'''

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

# email = ""

# siteStartYear = 2006

# favicon = "favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# showPrevNextPost = true

# [params.navItems]

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"